import assert from "node:assert/strict";
import { spawnSync } from "node:child_process";
import { existsSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import test from "node:test";

const SCRIPT = join(
  process.cwd(),
  "plugins/transcript/skills/transcript/scripts/strip-transcript.mjs"
);

function run(args = [], options = {}) {
  return spawnSync(process.execPath, [SCRIPT, ...args], {
    encoding: "utf8",
    ...options
  });
}

test("dedupes overlapping cues from stdin", () => {
  const input = `WEBVTT

00:00:00.000 --> 00:00:01.000
Hello

00:00:01.000 --> 00:00:02.000
Hello world.

00:00:02.000 --> 00:00:03.000
Hello world. Dr. Smith left.
`;

  const result = run(["--dedup"], { input });

  assert.equal(result.status, 0);
  assert.equal(result.stderr, "");
  assert.equal(result.stdout, "Hello world.\n\nDr. Smith left.\n");
});

for (const format of ["srt", "vtt"]) {
  test(`preserves repeated speech in ${format} by default`, () => {
    const input = `1
00:00:00.000 --> 00:00:01.000
Stop.

2
00:00:02.000 --> 00:00:03.000
Stop.

3
00:00:04.000 --> 00:00:05.000
Is that so

4
00:00:06.000 --> 00:00:07.000
so what happened next?
`;

    const result = run(["--format", format], { input });

    assert.equal(result.status, 0);
    assert.equal(result.stderr, "");
    assert.equal(result.stdout, "Stop.\n\nStop.\n\nIs that so so what happened next?\n");
  });
}

test("removes VTT cue identifiers and short timestamps, preserving payload", () => {
  const input = `WEBVTT

intro
00:01.000 --> 00:02.000 align:start
Hello <00:01.500><b>world.</b>
42

2
00:00:03.000 --> 00:00:04.000
Next line.
`;

  const result = run([], { input: input.replace(/\n/g, "\r\n") });

  assert.equal(result.status, 0);
  assert.equal(result.stderr, "");
  assert.equal(result.stdout, "Hello world. 42 Next line.\n");
});

test("removes SRT indices while preserving numeric dialogue", () => {
  const input = `1
00:00:00,000 --> 00:00:01,000
42

2
00:00:02,000 --> 00:00:03,000
The answer is
123
`;

  const result = run(["--format", "srt"], { input });

  assert.equal(result.status, 0);
  assert.equal(result.stderr, "");
  assert.equal(result.stdout, "42 The answer is 123\n");
});

test("preserves auto-caption text after space-only lines", () => {
  const input = `WEBVTT

00:00:00.060 --> 00:00:03.080 align:start position:0%
${" "}
<c>okay<00:00:00.690><c> so</c> this is a newsflash</c>
`;

  for (const newline of ["\n", "\r\n"]) {
    for (const args of [[], ["--dedup"]]) {
      const result = run(args, { input: input.replace(/\n/g, newline) });

      assert.equal(result.status, 0);
      assert.equal(result.stderr, "");
      assert.equal(result.stdout, "okay so this is a newsflash\n");
    }
  }
});

test("removes subtitle alignment codes without removing ordinary braces", () => {
  const input = `1
00:00:01,000 --> 00:00:02,000
<font size="20">{\\an8}Hello.</font>

2
00:00:03,000 --> 00:00:04,000
{\\an2}Keep {these words}.
`;

  const result = run(["--format", "srt"], { input });

  assert.equal(result.status, 0);
  assert.equal(result.stderr, "");
  assert.equal(result.stdout, "Hello.\n\nKeep {these words}.\n");
});

test("skips VTT NOTE/STYLE/REGION blocks", () => {
  const input = `WEBVTT

STYLE
::cue { color: lime; }

NOTE generated by uploader
This should not appear.

REGION
id:bottom
lines:3

00:00:00.000 --> 00:00:01.000
Hello world.
`;

  const result = run([], { input });

  assert.equal(result.status, 0);
  assert.equal(result.stdout, "Hello world.\n");
});

test("writes alongside the source and strips trailing language tags", () => {
  const dir = mkdtempSync(join(tmpdir(), "strip-transcript-"));
  const input = join(dir, "Talk.pt-BR.vtt");

  try {
    writeFileSync(input, `WEBVTT\n\n00:00:00.000 --> 00:00:01.000\nOlá mundo.\n`);

    const result = run(["--in-place", input]);
    const output = join(dir, "Talk.txt");

    assert.equal(result.status, 0);
    assert.equal(result.stdout.trim(), output);
    assert.equal(existsSync(input), false);
    assert.equal(readFileSync(output, "utf8"), "Olá mundo.\n");
  } finally {
    rmSync(dir, { recursive: true, force: true });
  }
});

test("rejects invalid CLI flags", () => {
  const result = run(["--wat"], { input: "" });

  assert.equal(result.status, 2);
  assert.match(result.stderr, /Unknown option: --wat/);
});

test("reports read errors cleanly", () => {
  const missing = join(tmpdir(), `missing-${Date.now()}.vtt`);
  const result = run([missing]);

  assert.equal(result.status, 1);
  assert.match(result.stderr, new RegExp(`Failed to read .*${missing.split("/").pop()}`));
});
