import assert from "node:assert/strict";
import { spawnSync } from "node:child_process";
import { existsSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import test from "node:test";

const SCRIPT = join(process.cwd(), "plugins/yt-dlp/skills/yt-dlp/scripts/strip-transcript.mjs");

function run(args = [], options = {}) {
  return spawnSync(process.execPath, [SCRIPT, ...args], {
    encoding: "utf8",
    ...options
  });
}

test("dedupes overlapping cues from stdin", () => {
  const input = `WEBVTT

00:00:00.000 --> 00:00:01.000
Hello

00:00:01.000 --> 00:00:02.000
Hello world.

00:00:02.000 --> 00:00:03.000
Hello world. Dr. Smith left.
`;

  const result = run([], { input });

  assert.equal(result.status, 0);
  assert.equal(result.stderr, "");
  assert.equal(result.stdout, "Hello world.\n\nDr. Smith left.\n");
});

test("skips VTT NOTE/STYLE/REGION blocks", () => {
  const input = `WEBVTT

STYLE
::cue { color: lime; }

NOTE generated by uploader
This should not appear.

REGION
id:bottom
lines:3

00:00:00.000 --> 00:00:01.000
Hello world.
`;

  const result = run([], { input });

  assert.equal(result.status, 0);
  assert.equal(result.stdout, "Hello world.\n");
});

test("writes alongside the source and strips trailing language tags", () => {
  const dir = mkdtempSync(join(tmpdir(), "strip-transcript-"));
  const input = join(dir, "Talk.pt-BR.vtt");

  try {
    writeFileSync(input, `WEBVTT\n\n00:00:00.000 --> 00:00:01.000\nOlá mundo.\n`);

    const result = run(["--in-place", input]);
    const output = join(dir, "Talk.txt");

    assert.equal(result.status, 0);
    assert.equal(result.stdout.trim(), output);
    assert.equal(existsSync(input), false);
    assert.equal(readFileSync(output, "utf8"), "Olá mundo.\n");
  } finally {
    rmSync(dir, { recursive: true, force: true });
  }
});

test("rejects invalid CLI flags", () => {
  const result = run(["--wat"], { input: "" });

  assert.equal(result.status, 2);
  assert.match(result.stderr, /Unknown option: --wat/);
});

test("reports read errors cleanly", () => {
  const missing = join(tmpdir(), `missing-${Date.now()}.vtt`);
  const result = run([missing]);

  assert.equal(result.status, 1);
  assert.match(result.stderr, new RegExp(`Failed to read .*${missing.split("/").pop()}`));
});
